trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'dirtykoyote/pipelines-javascript-docker'

steps:

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    containerRegistry: 'MyDockerHub'
    command: 'login'

- task: Docker@2
  inputs:
    repository: $(imageName)
    containerRegistry: 'MyDockerHub'
    command: buildAndPush
    Dockerfile: app/Dockerfile

