trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'dirtykoyote/pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

- task: Docker@2
  inputs:
    containerRegistry: 'MyDockerHub'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'MyDockerHub'
    command: 'push'
    tags: 'dirtykoyote/pipelines-javascript-docker:$(Build.BuildId)'
